# Generated by Django 4.2.7 on 2025-11-17 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('entidad', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('BOMBEROS', 'Bomberos'), ('AMBULANCIA', 'Ambulancia'), ('POLICIA', 'Policía'), ('DEFENSA_CIVIL', 'Defensa Civil'), ('HOSPITAL', 'Hospital'), ('OTRO', 'Otro')], max_length=30)),
                ('telefono_principal', models.CharField(max_length=15)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('tiempo_llegada_estimado', models.IntegerField(blank=True, help_text='Minutos estimados de llegada', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden_contacto', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Contacto Externo',
                'verbose_name_plural': 'Contactos Externos',
                'ordering': ['orden_contacto', 'tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('descripcion_ubicacion', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('REPORTADA', 'Reportada'), ('EN_ATENCION', 'En atención'), ('CONTROLADA', 'Controlada'), ('RESUELTA', 'Resuelta'), ('FALSA_ALARMA', 'Falsa alarma')], default='REPORTADA', max_length=20)),
                ('fecha_hora_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_atencion', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_resolucion', models.DateTimeField(blank=True, null=True)),
                ('acciones_tomadas', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='emergencias/')),
                ('personas_afectadas', models.IntegerField(default=0)),
                ('requiere_evacuacion', models.BooleanField(default=False)),
                ('entidades_externas_notificadas', models.TextField(blank=True)),
                ('atendida_por', models.ManyToManyField(blank=True, related_name='emergencias_atendidas', to=settings.AUTH_USER_MODEL)),
                ('edificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias', to='mapas.edificiobloque')),
                ('reportada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_reportadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergencia',
                'verbose_name_plural': 'Emergencias',
                'ordering': ['-fecha_hora_reporte'],
            },
        ),
        migrations.CreateModel(
            name='TipoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('color', models.CharField(default='#FF0000', max_length=7)),
                ('icono', models.CharField(default='warning', max_length=50)),
                ('prioridad', models.IntegerField(choices=[(1, 'Crítica'), (2, 'Alta'), (3, 'Media'), (4, 'Baja')], default=3)),
                ('protocolo', models.TextField(help_text='Pasos a seguir')),
                ('tiempo_respuesta_minutos', models.IntegerField(default=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de emergencia',
                'verbose_name_plural': 'Tipos de emergencias',
                'ordering': ['prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.CharField(choices=[('APP', 'Notificación App'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('LLAMADA', 'Llamada')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('emergencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='emergencias.emergencia')),
            ],
            options={
                'verbose_name': 'Notificación de Emergencia',
                'verbose_name_plural': 'Notificaciones de Emergencia',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AddField(
            model_name='emergencia',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergencias', to='emergencias.tipoemergencia'),
        ),
        migrations.CreateModel(
            name='BrigadaEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especializacion', models.CharField(choices=[('PRIMEROS_AUXILIOS', 'Primeros Auxilios'), ('INCENDIOS', 'Control de Incendios'), ('EVACUACION', 'Evacuación'), ('RESCATE', 'Rescate'), ('COMUNICACIONES', 'Comunicaciones'), ('GENERAL', 'General')], max_length=50)),
                ('nivel_certificacion', models.CharField(choices=[('BASICO', 'Básico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='BASICO', max_length=20)),
                ('fecha_certificacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('disponible', models.BooleanField(default=True)),
                ('telefono_emergencia', models.CharField(max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brigada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Brigada',
                'verbose_name_plural': 'Miembros de Brigada',
                'ordering': ['usuario__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='emergencia',
            index=models.Index(fields=['-fecha_hora_reporte'], name='emergencias_fecha_h_c292cb_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencia',
            index=models.Index(fields=['estado'], name='emergencias_estado_704786_idx'),
        ),
    ]
